<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SVM ( Support Vector Machine )**

In [2]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression


import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.discrete.discrete_model import MNLogit

from sklearn.tree import DecisionTreeClassifier

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

## **SVM for Classification**

In [4]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='diabetes')
df = df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop(['Outcome'],axis=1)
y = df['Outcome']

diet_dummy = pd.get_dummies(x.DietType,prefix='DT').astype(int)
x = x.drop(['DietType'],axis=1,inplace=True)
x = pd.concat([x,diet_dummy],axis=1)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=20)

In [6]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
svc = SVC()

params = {
    'C':[2,4,6,8,10],
    'kernel':['rbf','linear','poly'],
    'degree':[1,2,3,4]}

svc_cv = GridSearchCV(estimator=svc,param_grid=params,cv=3,scoring='accuracy')
svc_cv.fit(x_train,y_train)

svc_cv.best_params_

{'C': 2, 'degree': 1, 'kernel': 'rbf'}

In [7]:
from sklearn.metrics import confusion_matrix
svc = SVC(C=2,degree=1,kernel='linear')
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)

print(confusion_matrix(y_test,y_pred))

[[99  2]
 [17 36]]


In [8]:
(99+36)/(99+36+17+2)

0.8766233766233766

## **SVM for Regression**

In [5]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name = 'SalesData')

#df = df[['Glucose', 'BloodPressure','Age','DietType','Outcome']]

x = df.drop('Sales', axis=1)
y = df.Sales


region_dummy = pd.get_dummies(x.Region, drop_first=True, prefix='DT').astype(int)
x.drop('Region', axis=1, inplace=True)
x = pd.concat([x,region_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [ ]:
from sklearn.svm import SVR
svr = SVR()


params = {'C':[2,4,6,8,10],
	  'kernel':['rbf','linear','poly'],
	  'degree':[1,2,3,4],
      'epsilon':[0.01,0.1,0.5,1,5,10]}

svr_cv = GridSearchCV(estimator=svr,param_grid=params,cv=3,scoring='accuracy')
svr_cv.fit(x_train,y_train)

svr_cv.best_params_


In [ ]:
svr = SVR(C=2, degree=1, kernel='linear', epsilon=0.1)
svr.fit(x_train,y_train)
#y_pred = svr.predict(x_test)
#rmse = (sum((y_pred-y_test)*2)/len(y_pred))*0.5

y_pred = svr.fit(x_train)
SSE = sum((y_pred-y_train)**2)  # unexplained
SST = sum((y_train-np.mean(y_train))**2)  # total variance
SSR = SST - SSE # explained
R2 = SSR/SST
R2

# **KNN ( K Nearest Neightbour)**

## **KNN Classifier**

In [3]:
from sklearn.neighbors import KNeighborsClassifier
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx', sheet_name = 'diabetes')
df = df[['Glucose', 'BloodPressure','Age','DietType','Outcome']]
x = df.drop('Outcome', axis=1)
y = df.Outcome

diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='DT').astype(int)
x.drop('DietType', axis=1, inplace=True)
x = pd.concat([x,diet_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [6]:
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
mod1 = KNeighborsClassifier(n_neighbors=2)
mod1.fit(x_train,y_train)
y_pred1 = mod1.predict(x_train)
print(confusion_matrix(y_train,y_pred1))

y_pred2 = mod1.predict(x_test)
print(confusion_matrix(y_test,y_pred2))

[[399   0]
 [ 97 118]]
[[89 12]
 [33 20]]


## **KNN Regresssion**

In [8]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name = 'SalesData')

#df = df[['Glucose', 'BloodPressure','Age','DietType','Outcome']]

x = df.drop('Sales', axis=1)
y = df.Sales


region_dummy = pd.get_dummies(x.Region, drop_first=True, prefix='DT').astype(int)
x.drop('Region', axis=1, inplace=True)
x = pd.concat([x,region_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=7)
knn_reg.fit(x_train, y_train)

y_pred = knn_reg.predict(x_train)
SSE = sum((y_pred-y_train)**2)  # unexplained
SST = sum((y_train-np.mean(y_train))**2)  # total variance
SSR = SST - SSE # explained
R2 = SSR/SST
R2

0.8306624791507224