<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

In [11]:
x1 = [4,8,7,6,9]
type(x1)

# Converting into array
a1 = np.array(x1)
type(a1)

numpy.ndarray

In [14]:
x2 = [6,9,1,3,2]

# Creating 2d array
a2 = np.array([x1,x2])
type(a2)
print(a2)

[[4 8 7 6 9]
 [6 9 1 3 2]]


In [31]:
x1 = list(range(11))
x1

# arange()
a1 = np.arange(11)
a1

a2 = np.arange(3,14)
a2

a3 = np.arange(5,24,3)
a3

a4 = np.arange(6,24,3)    # last = 21
a4

a5 = np.arange(24,5,-1)   # last = 6
a5

a6 = np.arange(24,5,-2)
a6

a7 = np.arange(1,-10,-2)
a7

array([ 1, -1, -3, -5, -7, -9])

In [35]:
# linspace() - this command will create a array with including start and end with gap range between two numbers as 3 argument.
x1 = np.linspace(10,30,7)
x1

x2 = np.linspace(10,30,7,endpoint=False)    # last value will be excluded
x2


array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143,
       24.28571429, 27.14285714])

In [60]:
a1 = np.array([4,8,6,5,9])
a1

np.append(a1,3)   # append() - add value at the end
a1    # original list is not modified

a1 = np.append(a1,3)
a1    # org is modified

a2 = np.array([2,9,8])
a3 = np.concatenate([a1,a2])    # concatenate() - merging two arrays
a3

x1 = np.array([3,6,5,7,8])
x1
x2 = np.insert(x1,3,9)
x2

np.delete(x2,2)
print(x2)

[3 6 5 9 7 8]


In [121]:
a1 = np.array([1,2,3,4,5,6,7,8])
len(a1)

a2 = a1.reshape(4,2)
print(a2)

a3 = a1.reshape(2,4)
print(a3)

a4 = a1.reshape(2,2,2)
print(a4)

a5 = np.array([1,2,3,4,5,6,7,8])
print(a5)
#x1 = a5.reshape(4,3)  # cannot reshape array of size 8 into shape (4,3)
x1 = a5.reshape(4,2)
print(x1)

print(a5.reshape(-1,1))   # 2d array with 1 column
print(a5.reshape(-1,2))   # 2 columns

print(a5.reshape(1,-1))   # 2d array with 1 row

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4 5 6 7 8]]


In [123]:
# accessing rows or columns or values
a1 = np.array([1,2,3,4,5,6,7,8])
x1 = a1.reshape(4,2)
print(x1)
print(x1[2])
print(x1[2,:])
print(x1[:,1])
print(x1[[2,3],:])
print(x1[:,[0,1]])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[5 6]
[5 6]

[2 4 6 8]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [120]:
# adding column and rows
a1 = np.array([1,2,3,4,5,6,7,8])
x1 = a1.reshape(4,2)

newcol = np.array([3,1,7,9])
newcol = newcol.reshape(-1,1)
print(newcol)

x2 = np.hstack([x1,newcol])
print(x1)

newrow = np.array([1,2])
x3 = np.vstack([x1,newrow])
print(x3)

x3 = np.insert(x3,1,[10,20],axis=0)   # inserting row -> axis=0
print(x3)

x3 = np.insert(x3,1,[11,12,13,14,15,16],axis=1)   # inserting col -> axis=1
print(x3)

x4=np.delete(x3,(1,2),axis=0)
print(x4)

x5=np.delete(x3,(2),axis=1)
print(x5)

[[3]
 [1]
 [7]
 [9]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]]
[[ 1  2]
 [10 20]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 1  2]]
[[ 1 11  2]
 [10 12 20]
 [ 3 13  4]
 [ 5 14  6]
 [ 7 15  8]
 [ 1 16  2]]
[[ 1 11  2]
 [ 5 14  6]
 [ 7 15  8]
 [ 1 16  2]]
[[ 1 11]
 [10 12]
 [ 3 13]
 [ 5 14]
 [ 7 15]
 [ 1 16]]


In [132]:
# Broadcasting -> broadcasting makes it possible to repeat the same operation across all the values
a1 = np.array([4,7,6,8,9])
a2 = np.array([4,2,7,6,3])
print(a1)
print(a2)

print(a1 + 5,end="\n\n")

a3 = 2*a1 + 5
print(a3,end="\n\n")

print(a1 + a2)

[4 7 6 8 9]
[4 2 7 6 3]
[ 9 12 11 13 14]

[13 19 17 21 23]

[ 8  9 13 14 12]


In [6]:
a1 = np.array([3,5,4,6,7,9,3,1,2,6,7,9])
len(a1)

a2 = a1.reshape(3,4)
print(a2,end="\n\n")

a3 = np.array([2,4,6,8])
print(a3,end="\n\n")

print(a2+a3,end="\n\n")   # operation across row wise

a4 = np.array([3,4,5])
a4 = a4.reshape(-1,1)
print(a4,end="\n\n")

print(a2+a4,end="\n\n")   # operation across column wise

[[3 5 4 6]
 [7 9 3 1]
 [2 6 7 9]]

[2 4 6 8]

[[ 5  9 10 14]
 [ 9 13  9  9]
 [ 4 10 13 17]]

[[3]
 [4]
 [5]]

[[ 6  8  7  9]
 [11 13  7  5]
 [ 7 11 12 14]]



In [26]:
# where() : input to np.where command is condition need to be checked. Output of the np.where command are the indeces where the condition is found to pe true
print(a1,end="\n\n")

print(a1[[1,3,7]],end="\n\n")     # for multipe value accessing use double [] brackets. for single element just one [].

# Q1 : Where are the values which are greater than 4
ind = np.where(a1>4)
print(ind[0], end="\n\n")
type(ind)

# Q2 : How many values are greater than 4
print(len(ind[0]),end="\n\n")
print((a1>4).sum(),end="\n\n")

# Q3 : What are the values which are greater than 4
print(a1[ind[0]],end="\n\n")

x1 = np.array([1,2,3,4,5,6,7,8,9])
r=np.where(a1%2==0)
print(r,end="\n\n")
print(len(r[0]),end="\n\n")


[3 5 4 6 7 9 3 1 2 6 7 9]

[5 6 1]

[ 1  3  4  5  9 10 11]

7

7

[5 6 7 9 6 7 9]

(array([2, 3, 8, 9]),)

4



In [9]:
x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns
print(x1,end="\n\n")

x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols
print(x2,end="\n\n")

x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally
print(x3,end="\n\n")

x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically
print(x4,end="\n\n")

b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
c = sorted(b)          #sorts the array in increasing order
print(c,end="\n\n")
c = sorted(b)[::-1]    # sorts the array in the decreasing order
print(c,end="\n\n")
print(np.sort(b),end="\n\n")     # also PRINTS the array in the increasing order, original array is unchanged

b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns
print(b,end="\n\n")
print(np.sort(b,axis=0),end="\n\n")   # row wise values will be changed. Column values are only rearranged
print(np.sort(b,axis=1),end="\n\n")   # column wise values will be changed. Row values are only rearranged

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19]]), array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])]

[array([[ 0,  1],
       [ 8,  9],
       [16, 17],
       [24, 25],
       [32, 33],
       [40, 41]]), array([[ 2],
       [10],
       [18],
       [26],
       [34],
       [42]]), array([[ 3,  4],
       [11, 12],
       [19, 20],
       [27, 28],
       [35, 36],
       [43, 44]]), array([[ 5,  6,  7],
       [13, 14, 15],
       [21, 22, 2

In [54]:
a = np.arange(10)
print(np.resize(a,(5,3)),end="\n\n")
print(np.resize(a,(3,2)),end="\n\n")

b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
b=b.reshape(3,4)
print(b,end="\n\n")

ind =  np.where(b>=4)
print(ind,end="\n\n")   # -> (array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))
                                  #row_position                         #col_position
print(len(ind),end="\n\n")

print(b[ind],end="\n\n")
print(b[ind[0],ind[1]],end="\n\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 0 1]
 [2 3 4]]

[[0 1]
 [2 3]
 [4 5]]

[[2 4 1 7]
 [6 5 9 8]
 [2 3 1 5]]

(array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))

2

[4 7 6 5 9 8 5]

[4 7 6 5 9 8 5]



In [58]:
r1 = [5,8,3]
r2 = r1*3
print(r2,end="\n\n")

a1 = np.array([2,6,5,4])
a2 = np.repeat(a1,3)
print(a2,end="\n\n")

a3 = np.repeat(a1,[2,4,3,2])
print(a3,end="\n\n")

[5, 8, 3, 5, 8, 3, 5, 8, 3]

[2 2 2 6 6 6 5 5 5 4 4 4]

[2 2 6 6 6 6 5 5 5 4 4]



In [63]:
a1 = np.array([4,8,2,0,0,3,3,10])
print(np.sort(a1),end="\n\n")

print(np.argsort(a1),end="\n\n")  # it will give indexes of element

print(a1[np.argsort(a1)],end="\n\n")

[ 0  0  2  3  3  4  8 10]

[3 4 2 5 6 0 1 7]

[ 0  0  2  3  3  4  8 10]



In [79]:
a1 = np.array([6,5,3,7,5,2,8,4,5,2,1])
print(len(a1))

print(np.unique(a1))

print(np.unique(a1,return_counts=True))

print(np.unique(a1,return_index=True))

print(np.where(a1==1),np.where(a1==2),np.where(a1==5))

11
[1 2 3 4 5 6 7 8]
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([1, 2, 1, 1, 3, 1, 1, 1]))
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([10,  5,  2,  7,  1,  0,  3,  6]))
(array([10]),) (array([5, 9]),) (array([1, 4, 8]),)
