<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DataFrame**

In [ ]:
import numpy as np
import pandas as pd
import os

In [ ]:
# get current directory
os.getcwd()

'/content'

In [ ]:
# change directory
os.chdir("/content/drive/MyDrive/CDAC")

In [ ]:
# loading dataset
df = pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData")

In [ ]:
# first 5 rows of dataset
print(df.head(),end='\n\n')

print(df.head(3))   # to get specific count of first rows

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27


In [ ]:
# last 5 rows of dataset
df.tail()

,MaterialID,Location,Quantity
45,DDBN-89,MWH-2,69
46,AXCP-78,MWH-2,85
47,AXCP-78,MWH-3,29
48,AXCP-78,MWH-1,75
49,DDBN-89,MWH-1,39


In [ ]:
# to get no. of rows and cols. return type is tuple
df.shape

(50, 3)

In [ ]:
# to get unique materialid from dataset
print(np.unique(df['MaterialID']),end='\n\n')

print(np.unique(df.MaterialID))

['AXCP-78' 'DDBN-89' 'GCVB-79' 'LXCV-21' 'SDRT-67' 'TMI-43T']

['AXCP-78' 'DDBN-89' 'GCVB-79' 'LXCV-21' 'SDRT-67' 'TMI-43T']


In [ ]:
# no. of materialid
len(np.unique(df.MaterialID))

6

In [ ]:
# no. of locations
print(np.unique(df.Location),end='\n\n')
print(len(np.unique(df.Location)))

['MWH-1' 'MWH-2' 'MWH-3' 'MWH-4' 'MWH-5']

5


In [ ]:
print(df.head(),end='\n\n')

print(df.columns.values,end='\n\n')     # list al column name

print(df.columns.values[0],end='\n\n')  # extracting single column name

df.columns.values[0]="MatId"            # renaming single column name
print(df.head(),end='\n\n')

df.columns.values[0]="MaterialID"
print(df.head())

     MatId Location  Quantity
0  TMI-43T    MWH-4        34
1  AXCP-78    MWH-1        67
2  LXCV-21    MWH-2        27
3  AXCP-78    MWH-5        65
4  AXCP-78    MWH-4        36

['MatId' 'Location' 'Quantity']

MatId

     MatId Location  Quantity
0  TMI-43T    MWH-4        34
1  AXCP-78    MWH-1        67
2  LXCV-21    MWH-2        27
3  AXCP-78    MWH-5        65
4  AXCP-78    MWH-4        36

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36


In [ ]:
# creating new df where quantity is greater then equal to 70
ind = np.where(df.Quantity>=70)
print("No. of rows where Quantity >= 70 (Methos 1): ",len(ind[0]),end='\n\n')

print("No. of rows where Quantity >= 70 (Methos 2): ",(df.Quantity>=70).sum(),end='\n\n')

df1 = df.iloc[ind]
print(df1, end='\n\n')

No. of rows where Quantity >= 70 (Methos 1):  15

No. of rows where Quantity >= 70 (Methos 2):  15

   MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

   MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
48    AXCP-78    MWH-1        75


In [ ]:
ind = np.where((df.Quantity>=70) & (df.Location=="MWH-1"))
print(len(ind[0]),end='\n\n')
print(df.iloc[ind],end='\n\n')

5

   MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
48    AXCP-78    MWH-1        75



In [ ]:
ind = np.where((df.Quantity>=70) | (df.Location=="MWH-1"))
print(len(ind[0]),end='\n\n')
print(df.iloc[ind],end='\n\n')

21

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39



In [ ]:
# what is the total weight of all consignment stored in MWH-2
ind = np.where(df.Location=="MWH-2")
print(ind)

print("the total weight of all consignment stored in MWH-2 : ",df.iloc[ind].Quantity.sum())

print("the total weight of all consignment stored in MWH-2 : ",df.iloc[np.where(df.Location=="MWH-2")].Quantity.sum())

print("the total weight of all consignment stored in MWH-2 : ",sum(df.iloc[np.where(df.Location=="MWH-2")].Quantity))

(array([ 2,  7,  8, 15, 35, 36, 42, 45, 46]),)
the total weight of all consignment stored in MWH-2 :  397
the total weight of all consignment stored in MWH-2 :  397
the total weight of all consignment stored in MWH-2 :  397


In [ ]:
# find out how many rows have quantity less then 50
print("Rows with quantity less then 50 :",len(np.where(df.Quantity<50)[0]))

Rows with quantity less then 50 : 24


In [ ]:
# remove rows where quantity value is less then 50
ind = np.where(df.Quantity<50)
df1 = df.drop(ind[0]).reset_index(drop=True)
print(len(df1))
df1

26


,MaterialID,Location,Quantity
0,AXCP-78,MWH-1,67
1,AXCP-78,MWH-5,65
2,TMI-43T,MWH-4,78
3,TMI-43T,MWH-1,120
4,SDRT-67,MWH-4,58
5,TMI-43T,MWH-4,76
6,TMI-43T,MWH-3,65
7,GCVB-79,MWH-2,87
8,SDRT-67,MWH-5,102
9,TMI-43T,MWH-4,52


In [ ]:
df.shape

(50, 3)

In [ ]:
# add new column based on condition
list = []
for i in df.Quantity:
  if i<=50:
    list.append("A")
  elif i<100:
    list.append("B")
  else:
    list.append("C")
print(list,end='\n\n')
df["Grade"]=list
print(df.head())

['A', 'B', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'C', 'A', 'B', 'B', 'A', 'B', 'B', 'A', 'C', 'A', 'B', 'A', 'B', 'A', 'B', 'C', 'C', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'C', 'A', 'A', 'A', 'B', 'B', 'C', 'A', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'A']

  MaterialID Location  Quantity Grade
0    TMI-43T    MWH-4        34     A
1    AXCP-78    MWH-1        67     B
2    LXCV-21    MWH-2        27     A
3    AXCP-78    MWH-5        65     B
4    AXCP-78    MWH-4        36     A


In [ ]:
# frequency of A,B,C grades
df.Grade.value_counts()

,count
Grade,
A,24
B,20
C,6


In [ ]:
# w.a.p the output of which is name of that warehouse  where total quantity is highest and that number is 590
inp = np.unique(df.Location)

for i in inp:
  print(i)

MWH-1
MWH-2
MWH-3
MWH-4
MWH-5


Data Cleaning

In [ ]:
df = pd.read_excel("CDAC_DataBook.xlsx",sheet_name="EmpInfo")
df

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,NaN,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,NaN,ER534867
6,Deepak,NaN,Quality,RF453432


In [ ]:
# find missing values
ind = np.where(df.Deptt.isnull())
print(ind)

df2 = df.iloc[ind[0]].reset_index(drop=True)      # select rows having missing values
print(df2,end='\n\n')

df1 = df.drop(ind[0]).reset_index(drop=True)      # select rows which are not having missing values
print(df1)

(array([3, 5]),)
     Name EmpID Deptt  Passport
0   Arjun  A342   NaN  RF453432
1  Chetan   NaN   NaN  ER534867

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Rishi  R475    Prodn  DF453278
4   Deepak   NaN  Quality  RF453432


In [ ]:
print(df,end='\n\n')
ind = np.where((df.EmpID.isnull()) & (df.Deptt.isnull()))
print(df.iloc[ind])

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

     Name EmpID Deptt  Passport
5  Chetan   NaN   NaN  ER534867


In [ ]:
# Handlinf missing values
# 1) remove rows -> no. of rows are few
# 2) replace the missing values with some other values
# -> int - median value
# -> string - mode value
ind = np.where(df.Deptt.isnull())
print(df,end='\n\n')
df.loc[ind[0],'Deptt']='Fresher'   # replace the missing value with word 'Fresher'
print(df,end='\n\n')

df.iloc[ind[0],2]='Fresher'
print(df)

      Name EmpID     Deptt  Passport
0   Sudeep  A342   Quality  DF453278
1  Ruchika  C578     Sales  CA567657
2      NaN  J436     Admin  DF453278
3    Arjun  A342  Freshers  RF453432
4    Rishi  R475     Prodn  DF453278
5   Chetan   NaN  Freshers  ER534867
6   Deepak   NaN   Quality  RF453432

      Name EmpID     Deptt  Passport
0   Sudeep  A342   Quality  DF453278
1  Ruchika  C578     Sales  CA567657
2      NaN  J436     Admin  DF453278
3    Arjun  A342  Freshers  RF453432
4    Rishi  R475     Prodn  DF453278
5   Chetan   NaN  Freshers  ER534867
6   Deepak   NaN   Quality  RF453432

      Name EmpID     Deptt  Passport
0   Sudeep  A342   Quality  DF453278
1  Ruchika  C578     Sales  CA567657
2      NaN  J436     Admin  DF453278
3    Arjun  A342  Freshers  RF453432
4    Rishi  R475     Prodn  DF453278
5   Chetan   NaN  Freshers  ER534867
6   Deepak   NaN   Quality  RF453432


In [ ]:
print(df.EmpID.isnull())
df.EmpID.isnull().sum()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
Name: EmpID, dtype: bool


np.int64(2)

In [ ]:
temp = df.dropna().reset_index(drop=True)
temp

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,Arjun,A342,Freshers,RF453432
3,Rishi,R475,Prodn,DF453278


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      6 non-null      object
 1   EmpID     5 non-null      object
 2   Deptt     7 non-null      object
 3   Passport  7 non-null      object
dtypes: object(4)
memory usage: 356.0+ bytes


In [ ]:
# handling duplicate values
print(df,end='\n\n')

ind = np.where(df.Passport.duplicated())
print(ind)

ind = np.where(df.Passport.duplicated(keep=False))  # we have to use keep=False because without this we only get 2nd occurance.  mostly used
print(ind)

ind = np.where(df.Passport.duplicated(keep='first'))  # first occurance reported
print(ind)

ind = np.where(df.Passport.duplicated(keep='last'))   # last occurance is not reported
print(ind)

      Name EmpID     Deptt  Passport
0   Sudeep  A342   Quality  DF453278
1  Ruchika  C578     Sales  CA567657
2      NaN  J436     Admin  DF453278
3    Arjun  A342  Freshers  RF453432
4    Rishi  R475     Prodn  DF453278
5   Chetan   NaN  Freshers  ER534867
6   Deepak   NaN   Quality  RF453432

(array([2, 4, 6]),)
(array([0, 2, 3, 4, 6]),)
(array([2, 4, 6]),)
(array([0, 2, 3]),)


Data Validation


In [ ]:
df = pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData")

In [ ]:
ind = np.where((df.Quantity>60) & (df.Quantity<100))
print(len(ind[0]))
df1 =  df.iloc[ind[0]]
print(df1)

15
   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
27    LXCV-21    MWH-5        83
31    TMI-43T    MWH-4        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75


# **GroupBy Command**


In [ ]:
grp1 = df.groupby('Location')
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [ ]:
grp1.get_group('MWH-2')

,MaterialID,Location,Quantity
2,LXCV-21,MWH-2,27
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
15,GCVB-79,MWH-2,87
35,GCVB-79,MWH-2,31
36,GCVB-79,MWH-2,28
42,SDRT-67,MWH-2,31
45,DDBN-89,MWH-2,69
46,AXCP-78,MWH-2,85


In [ ]:
df1 = grp1.get_group('MWH-2').reset_index(drop=True)
df1

,MaterialID,Location,Quantity
0,LXCV-21,MWH-2,27
1,TMI-43T,MWH-2,29
2,GCVB-79,MWH-2,10
3,GCVB-79,MWH-2,87
4,GCVB-79,MWH-2,31
5,GCVB-79,MWH-2,28
6,SDRT-67,MWH-2,31
7,DDBN-89,MWH-2,69
8,AXCP-78,MWH-2,85


In [ ]:
pd.concat([grp1.get_group('MWH-2'),grp1.get_group('MWH-3')])

,MaterialID,Location,Quantity
2,LXCV-21,MWH-2,27
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
15,GCVB-79,MWH-2,87
35,GCVB-79,MWH-2,31
36,GCVB-79,MWH-2,28
42,SDRT-67,MWH-2,31
45,DDBN-89,MWH-2,69
46,AXCP-78,MWH-2,85
14,TMI-43T,MWH-3,65


In [ ]:
df1 = grp1.Quantity.agg(np.sum)       # to find total
df1

/tmp/ipykernel_1603/1360066800.py:1: FutureWarning: The provided callable <function sum at 0x7d926c538860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1 = grp1.Quantity.agg(np.sum)


,Quantity
Location,
MWH-1,889
MWH-2,397
MWH-3,174
MWH-4,728
MWH-5,697


In [ ]:
df1.reset_index()

,Location,Quantity
0,MWH-1,889
1,MWH-2,397
2,MWH-3,174
3,MWH-4,728
4,MWH-5,697


In [ ]:
grp1.Quantity.agg(np.size)       # to find frequency

,Quantity
Location,
MWH-1,11
MWH-2,9
MWH-3,4
MWH-4,15
MWH-5,11


In [ ]:
grp1.Quantity.agg(np.mean)      # to find avg

/tmp/ipykernel_1603/719844975.py:1: FutureWarning: The provided callable <function mean at 0x7d926c539940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg(np.mean)


,Quantity
Location,
MWH-1,80.818182
MWH-2,44.111111
MWH-3,43.500000
MWH-4,48.533333
MWH-5,63.363636


In [ ]:
grp1.Quantity.agg(['sum','mean','size'])

,sum,mean,size
Location,,,
MWH-1,889,80.818182,11
MWH-2,397,44.111111,9
MWH-3,174,43.500000,4
MWH-4,728,48.533333,15
MWH-5,697,63.363636,11


In [ ]:
locn1 = ['Mumbai','Mumbai','Mumbai','Pune','Pune']
course = ['AI','ML','DS','AI','DS']
marks1 = [45,78,65,35,89]
marks2 = [80,76,59,82,49]

mydf = pd.DataFrame({'Sujal':marks1,'Rupi':marks2},index=[locn1,course])
mydf

Sujal  Rupi
Mumbai AI     45    80
       ML     78    76
       DS     65    59
Pune   AI     35    82
       DS     89    49

In [ ]:
mydf.index.names = ['Location','Subject']
mydf

Sujal  Rupi
Location Subject             
Mumbai   AI          45    80
         ML          78    76
         DS          65    59
Pune     AI          35    82
         DS          89    49

In [ ]:
mydf.loc['Mumbai']

,Sujal,Rupi
Subject,,
AI,45,80
ML,78,76
DS,65,59


In [ ]:
mydf.loc[('Mumbai','AI')]

,Mumbai
,AI
Sujal,45
Rupi,80


In [ ]:
mydf.xs('AI',level='Subject')

,Sujal,Rupi
Location,,
Mumbai,45,80
Pune,35,82
