<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Unsupervised_Day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression


import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.discrete.discrete_model import MNLogit

from sklearn.tree import DecisionTreeClassifier

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [6]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/pca.xlsx')
df.head()

x = df.drop(columns=["Response"])
y = df.Response
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)
x_train = sm.add_constant(x_train, prepend=False)

mod1 = sm.Logit(y_train,x_train).fit()
print(mod1.summary())

Optimization terminated successfully.
         Current function value: 0.170808
         Iterations 10
                           Logit Regression Results                           
Dep. Variable:               Response   No. Observations:                  400
Model:                          Logit   Df Residuals:                      393
Method:                           MLE   Df Model:                            6
Date:                Sat, 20 Jun 2026   Pseudo R-squ.:                  0.7510
Time:                        06:10:09   Log-Likelihood:                -68.323
converged:                       True   LL-Null:                       -274.37
Covariance Type:            nonrobust   LLR p-value:                 7.004e-86
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.1179      0.143      0.827      0.408      -0.162       0.397
X2             0.3496      0

In [7]:
x_test = sm.add_constant(x_test, prepend=False)
y_pred = mod1.predict(x_test)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_test,y_pred))
# % accuracy on test dataset is 93%

[[49  4]
 [ 3 44]]


In [5]:
y_pred = mod1.predict(x_train)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_train,y_pred))
# % accuracy on train dataset is 93%

[[161  15]
 [ 13 211]]


### **Apply PCA**

In [8]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/pca.xlsx')
df.head()

x = df.drop(columns=["Response"])
y = df.Response
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

**Standardizing values**

In [11]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)

**Correlation Matrix**

In [12]:
cov_matrix = np.cov(x_train_scaled.T)
print(cov_matrix)

[[ 1.00250627  0.99459513 -0.01762116 -0.01881352  0.02875781  0.02221232]
 [ 0.99459513  1.00250627 -0.02295467 -0.0241789   0.02011072  0.01316072]
 [-0.01762116 -0.02295467  1.00250627  0.99486306  0.07523883  0.06273846]
 [-0.01881352 -0.0241789   0.99486306  1.00250627  0.07171426  0.05852582]
 [ 0.02875781  0.02011072  0.07523883  0.07171426  1.00250627  0.9944493 ]
 [ 0.02221232  0.01316072  0.06273846  0.05852582  0.9944493   1.00250627]]


**Calculating EigenValues and EigenVectors using covariance methos**

In [17]:
eigen_values,eigen_vectors = np.linalg.eig(cov_matrix)
print(eigen_values)
print()
print(eigen_vectors)

[1.84063633 2.01959558 2.13136156 0.00825781 0.0073606  0.00782571]

[[ 0.24965379 -0.66152585  0.00461231  0.30774795  0.22118585 -0.59699521]
 [ 0.25144885 -0.66092036 -0.00207284 -0.30406518 -0.22463094  0.59752721]
 [ 0.46618233  0.17720023  0.50113026  0.30055577  0.53283546  0.3548171 ]
 [ 0.46782942  0.17867247  0.49930911 -0.29454835 -0.53907789 -0.35005498]
 [-0.46389634 -0.17749278  0.50278694 -0.56597836  0.4020033  -0.1362484 ]
 [-0.47228838 -0.1753293   0.49672789  0.56161514 -0.40557675  0.13985944]]


In [14]:
sum(eigen_values)

np.float64(6.015037593984967)

In [16]:
(2.01959558 + 2.13136156)/6

0.69182619

In [18]:
np.dot(eigen_vectors[:,2],eigen_vectors[:,1])

np.float64(0.0)

### **PCA using in built in commands**

In [20]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/pca.xlsx')
df.head()
x = df.drop(columns=["Response"])
y = df.Response
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [21]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)

In [23]:
from sklearn.decomposition import PCA
pca= PCA()
pca.fit(x_train_scaled)

PCA()

**Calculating EigenValues and EigenVectors using PCA method**

In [24]:
eig_pca = pca.explained_variance_
eig_pca   # eigen values in descending order

array([2.13136156, 2.01959558, 1.84063633, 0.00825781, 0.00782571,
       0.0073606 ])

In [26]:
eigen_vect = pca.components_.T   # eigen vectors
eigen_vect

array([[ 0.00461231,  0.66152585, -0.24965379, -0.30774795, -0.59699521,
        -0.22118585],
       [-0.00207284,  0.66092036, -0.25144885,  0.30406518,  0.59752721,
         0.22463094],
       [ 0.50113026, -0.17720023, -0.46618233, -0.30055577,  0.3548171 ,
        -0.53283546],
       [ 0.49930911, -0.17867247, -0.46782942,  0.29454835, -0.35005498,
         0.53907789],
       [ 0.50278694,  0.17749278,  0.46389634,  0.56597836, -0.1362484 ,
        -0.4020033 ],
       [ 0.49672789,  0.1753293 ,  0.47228838, -0.56161514,  0.13985944,
         0.40557675]])

---

In [27]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/pca.xlsx')
df.head()
x = df.drop(columns=["Response"])
y = df.Response
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [56]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


In [55]:
pca = PCA(n_components=2)
xtrain_pca = pca.fit_transform(x_train_scaled)
xtest_pca = pca.transform(x_test_scaled)


In [30]:
xtrain_pca = pd.DataFrame(xtrain_pca,columns=['PC1','PC2'],index=x_train.index)
xtest_pca = pd.DataFrame(xtest_pca,columns=['PC1','PC2'],index=x_test.index)

In [31]:
xtrain_pca.head()

,PC1,PC2
115,-0.646004,-1.394481
80,1.088695,-0.475172
30,1.897835,-1.360675
445,0.526909,1.496927
379,0.525213,0.480849


In [32]:
x_train_pc1 = sm.add_constant(xtrain_pca, prepend=False)
x_test_pc1 = sm.add_constant(xtest_pca, prepend=False)

In [37]:
from statsmodels.discrete.discrete_model import MNLogit
mod2pca = sm.Logit(y_train,x_train_pc1).fit()

Optimization terminated successfully.
         Current function value: 0.359350
         Iterations 7


In [45]:
y_pred = mod2pca.predict(x_test_pc1)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_test,y_pred))

[[43 10]
 [12 35]]


In [47]:
(43+35)/(43+35+10+12)

0.78

In [46]:
y_pred = mod2pca.predict(x_train_pc1)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_train,y_pred))

[[137  39]
 [ 27 197]]


In [48]:
(137+197)/(137+197+39+27)

0.835