<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day23/24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression


import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.discrete.discrete_model import MNLogit

from sklearn.tree import DecisionTreeClassifier

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx",sheet_name="diabetes")
df.columns

Index(['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age', 'Outcome', 'DietType'],
      dtype='object')

In [ ]:
df = df[['Glucose','BloodPressure','Age','DietType','Outcome']]
diet_dummy = pd.get_dummies(df.DietType, drop_first=True).astype(int)
df = df.drop('DietType', axis=1)
df = pd.concat([df,diet_dummy], axis=1)

In [ ]:
df.head()

,Glucose,BloodPressure,Age,Outcome,2,3
0,148,72,50,1,0,0
1,85,66,31,0,1,0
2,183,64,32,1,0,0
3,89,66,21,0,0,0
4,137,40,33,1,0,0


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop('Outcome', axis=1), df.Outcome, test_size=0.2, random_state=20)

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.models import Sequential # helps with the forward and backward propagation
from tensorflow.keras.layers import Dense # this is for the hidden, input and output layers
from tensorflow.keras.layers import ReLU   # activation function
from tensorflow.keras.layers import Dropout   # switching off the neurons

In [ ]:
classifier = Sequential()
classifier.add(Dense(units=5, activation='relu', input_dim=5))    # input layer of 5 neurons
classifier.add(Dense(units=7, activation='relu'))                 # first hidden layer with 7 neurons
classifier.add(Dense(units=5, activation='relu'))                 # second hidden layer with 5 neurons
classifier.add(Dense(units=1, activation='sigmoid'))              # output layer

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
mod1 = classifier.fit(x_train, y_train, batch_size=10, epochs=10)

Epoch 1/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3502 - loss: 2.9576
Epoch 2/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3485 - loss: 1.5029
Epoch 3/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3388 - loss: 0.9832
Epoch 4/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3388 - loss: 0.8211
Epoch 5/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3404 - loss: 0.7597
Epoch 6/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3762 - loss: 0.7222
Epoch 7/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5570 - loss: 0.6987
Epoch 8/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6612 - loss: 0.6832
Epoch 9/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6971 - loss: 0.6726
Epoch 10/10
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6857 - loss: 0.6567


In [ ]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred >= 0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step


array([[82, 19],
       [39, 14]])

# **Naive Bayes Classifier**

In [ ]:
import sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx', sheet_name = 'diabetes')
x= df.drop('Outcome', axis=1)  # column of predictors
y= df.Outcome   # column of response

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

gnb = GaussianNB()

mod1 = gnb.fit(x_train,y_train)

y_pred = mod1.predict(x_test)
print(y_pred)

print(confusion_matrix(y_test,y_pred))

[0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0
 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 1
 0 0 0 1 0 0 0]
[[106  17]
 [ 15  54]]


In [ ]:
# Accuracy
(106+54)/(106+54+17+15)

0.8333333333333334

In [ ]:
y_pred1 = mod1.predict(x_train)
print(y_pred1)

[1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1
 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0
 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 1 1 0 1
 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1
 0 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0
 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0
 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0
 1 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1
 1 0 0 1 0 1 0 0 1 1 0 1 

In [ ]:
print(confusion_matrix(y_train,y_pred1))

[[340  37]
 [ 45 154]]


In [ ]:
# Accuracy
(340+154)/(340+154+37+45)

0.8576388888888888

## **Example 2**

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx', sheet_name = 'iris')
x= df.drop('Species', axis=1)  # column of predictors
y= df.Species   # column of response

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

gnb = GaussianNB()

mod1 = gnb.fit(x_train,y_train)

y_pred = mod1.predict(x_test)

print(confusion_matrix(y_test,y_pred))

[[13  0  0]
 [ 0 10  2]
 [ 0  2 11]]
